### ISSUE TITLE
problems deploying to heroku

### ISSUE THREAD

**Issue by carolinasno** [carolinasno/awshucks#1]
I'm getting an Application Error for awshucks. 

![screen shot 2016-02-16 at 11 17 46 am](https://cloud.githubusercontent.com/assets/15617759/13082502/f0f82aa0-d49e-11e5-8a49-aae0fffd8490.png)

For kindOrandom, the app isn't working.

![screen shot 2016-02-16 at 11 20 23 am](https://cloud.githubusercontent.com/assets/15617759/13082616/5cef5170-d49f-11e5-8381-f2426e4047b9.png)

Currently working on getting inseason up on DigitalOcean, which I'm sure will have its own issues.

**Comment by rapala61** [comment]
in person
